CREATE TABLE "Word_Words"
(
    id serial NOT NULL,
    word character varying(45) COLLATE pg_catalog."default",
    category character(1) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Word_Words_pkey" PRIMARY KEY (id, category),
    CONSTRAINT unique_key_word UNIQUE (word, category)
) PARTITION BY LIST (category);

CREATE TABLE "A" PARTITION OF "Word_Words" FOR VALUES IN ('A');
CREATE TABLE "B" PARTITION OF "Word_Words" FOR VALUES IN ('B');
CREATE TABLE "C" PARTITION OF "Word_Words" FOR VALUES IN ('C');
CREATE TABLE "D" PARTITION OF "Word_Words" FOR VALUES IN ('D');
CREATE TABLE "E" PARTITION OF "Word_Words" FOR VALUES IN ('E');
CREATE TABLE "F" PARTITION OF "Word_Words" FOR VALUES IN ('F');
CREATE TABLE "G" PARTITION OF "Word_Words" FOR VALUES IN ('G');
CREATE TABLE "H" PARTITION OF "Word_Words" FOR VALUES IN ('H');
CREATE TABLE "I" PARTITION OF "Word_Words" FOR VALUES IN ('I');
CREATE TABLE "J" PARTITION OF "Word_Words" FOR VALUES IN ('J');
CREATE TABLE "K" PARTITION OF "Word_Words" FOR VALUES IN ('K');
CREATE TABLE "L" PARTITION OF "Word_Words" FOR VALUES IN ('L');
CREATE TABLE "M" PARTITION OF "Word_Words" FOR VALUES IN ('M');
CREATE TABLE "N" PARTITION OF "Word_Words" FOR VALUES IN ('N');
CREATE TABLE "O" PARTITION OF "Word_Words" FOR VALUES IN ('O');
CREATE TABLE "P" PARTITION OF "Word_Words" FOR VALUES IN ('P');
CREATE TABLE "Q" PARTITION OF "Word_Words" FOR VALUES IN ('Q');
CREATE TABLE "R" PARTITION OF "Word_Words" FOR VALUES IN ('R');
CREATE TABLE "S" PARTITION OF "Word_Words" FOR VALUES IN ('S');
CREATE TABLE "T" PARTITION OF "Word_Words" FOR VALUES IN ('T');
CREATE TABLE "U" PARTITION OF "Word_Words" FOR VALUES IN ('U');
CREATE TABLE "V" PARTITION OF "Word_Words" FOR VALUES IN ('V');
CREATE TABLE "W" PARTITION OF "Word_Words" FOR VALUES IN ('W');
CREATE TABLE "X" PARTITION OF "Word_Words" FOR VALUES IN ('X');
CREATE TABLE "Y" PARTITION OF "Word_Words" FOR VALUES IN ('Y');
CREATE TABLE "Z" PARTITION OF "Word_Words" FOR VALUES IN ('Z');