FROM python:3.7-alpine
RUN apk update && apk add python3-dev \
    gcc \
    libc-dev \
    libffi-dev \
    openssl-dev
WORKDIR /code
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENVIRONMENT=development
ENV FLASK_DEBUG=1
COPY ./server/requirements.txt requirements.txt
RUN python3 -m pip install -r requirements.txt --no-cache-dir
EXPOSE 5000